### PR TITLE
Removing comments

### PR DESCRIPTION
**Pull request by tm01013**
### Hi, I'm the creator of '[how-to-make-your-own-crypto](https://github.com/tm01013/how-to-make-your-own-crypto)'.
I'm saw you used an **_old version_** of my code, witch has some issues.
By removeing my comments (starting with //) **everithing will work fine.**
**This issue got fixed now.**

> If it not work please **post an issue** in my repo.

Thanks for using my code :)

### CODE REVIEW

**Comment by frag-gen** [comment]
Hi,
Great to talk to you, if you are okay with it, can we talk over any
messaging service, whatsApp Or any other?
If you could, please help me through this, I'm trying to implement an idea
of mine.

Lmk if you would be down to know more.

**Comment by tm01013** [comment]
Yes, I can help you. Whats your problem?

**Comment by frag-gen** [comment]
I'm trying to build a digital currency for my campus as a project. I need
help with that.
It will be easier if we could communicate over a better platform.?
Discord or whatsapp or anything else.

**Comment by tm01013** [comment]
Ok I we can use discord. [https://discord.gg/nzhnnSYr](https://discord.gg/nzhnnSYr)

**Comment by frag-gen** [comment]
great! i have joined.

**Comment by frag-gen** [comment]
can u reply on discord??

**Comment by tm01013** [comment]
No :( it give me an error

**Comment by tm01013** [comment]
Marge this pullreqest and everithing will work

**Comment by frag-gen** [comment]
i cant dm u

**Comment by tm01013** [comment]
Eeverithing in my repo

**Pull request closed without merging**
